# Generated by Django 5.0.6 on 2024-09-02 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('add', models.IntegerField()),
                ('reason', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('late', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('adds', models.ManyToManyField(related_name='premium_adds', to='premium.add')),
                ('bids', models.ManyToManyField(related_name='premium_bids', to='premium.bid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='premium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_premium', to='premium.premium'),
        ),
        migrations.AddField(
            model_name='add',
            name='premium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_premium', to='premium.premium'),
        ),
    ]
