# Generated by Django 5.0.6 on 2024-09-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0003_premium_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premium',
            name='adds',
        ),
        migrations.AddField(
            model_name='bid',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='reason',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='Add',
        ),
    ]
