# Generated by Django 5.0.6 on 2024-09-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0004_remove_premium_adds_bid_price_bid_reason_delete_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='cara',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
