# Generated by Django 5.0.6 on 2024-09-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0005_bid_cara'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='price',
            new_name='new_price',
        ),
        migrations.AddField(
            model_name='bid',
            name='old_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
